DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS group_users;
DROP TABLE IF EXISTS bills CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users_items;